name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy"
        required: false
        default: "latest"

jobs:
  manual-deploy:
    name: Manual Deploy to AWS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Terraform Apply
        env:
          TF_VAR_image_tag: ${{ github.event.inputs.image_tag }}
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
        run: terraform -chdir=infra apply -input=false -auto-approve

      - name: Capture Terraform Outputs
        id: tf-out
        run: |
          terraform -chdir=infra output -json > tf_outputs.json
          cat tf_outputs.json

      - name: Post Deployment Summary
        run: |
          URL=$(jq -r '.apprunner_service_url.value' tf_outputs.json)
          IMAGE=$(jq -r '.deployed_image.value' tf_outputs.json)

          echo "## 🚀 Manual Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Service URL:** [$URL]($URL)" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployed Image:** \`$IMAGE\`" >> $GITHUB_STEP_SUMMARY

